services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - cobrefacil-network
    environment:
      YII_ENV: dev
      YII_DEBUG: 1
    working_dir: /var/www

  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - cobrefacil-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cobrefacil
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cobrefacil-network

networks:
  cobrefacil-network:

volumes:
  dbdata:
